### ISSUE TITLE
Availability of "The Design of a Self-Compiling C Transpiler Targeting POSIX Shell"

### ISSUE THREAD

**Issue by maconcg** [udem-dlteam/pnut#90]
Hi,

I recently came across this paper, which is linked to from Profs. Monnier & Feeley's respective umontreal pages.  Neither link currently works, however.

This may be because the official publication date is October 2024, in which case pay me no attention.  But one link gives the impression that it should be available at `~feeley/papers/HuberdeauMonnierFeeleySLE24.pdf`, so I thought it might be worth creating an issue.

**Comment by feeley** [comment]
Indeed the reference to pnut on my web page was a placeholder for the PDF.

The preprint is now available here: http://www-labs.iro.umontreal.ca/~feeley/papers/HuberdeauHamelMonnierFeeleySLE24.pdf

**Comment by maconcg** [comment]
Thank you!
